config/routes.rb
Reader::Application.routes.draw do
  get "add_feed" => "add_feed#new"
  post "add_feed/create"

  get "about" => "pages#about", :as => :about

  devise_for :users

  get "dashboard" => "dashboard#index"

  root :to => "home#index"

end

app/models/feed.rb
# encoding: utf-8

require 'open-uri'
require 'htmlentities'

class Feed < ActiveRecord::Base
  has_many :feed_items
  has_and_belongs_to_many :users

  # url of rss feed
  validates :url, presence: true
  # rss.channel.link
  validates :link, presence: true, unless: "new_record?"
  # rss.channel.title
  validates :title, presence: true, unless: "new_record?"

  def self.add_feed(url, user)
    unless Feed.feed_exists?(url)
      feed = Feed.create(url: url)
      feed.delay.update_link_and_title
    end
    user.feeds << Feed.where(url: url).first
  end

  def self.feed_exists?(url)
    if Feed.where(url: url).first
      true
    else
      false
    end
  end

  def update_link_and_title
    rss = SimpleRSS.parse(open(url))
    self.link = rss.channel.link
    self.title = rss.channel.title
    self.save!
    self.delay.update_feed_items
  end

  def update_feed_items
    rss = SimpleRSS.parse(open(url))
    rss.items.each do |item|
      FeedItem.create!(feed_id: self.id,
                       title: item.title,
                       link: item.link,
                       #author: item.author,
                       body: HTMLEntities.new.decode(item.description))
                       #date: item.pubDate,
                       #guid: item.guid,
                       #feedburner_origLink)
    end
  end
end

app/models/feed_item.rb
# encoding: utf-8

class FeedItem < ActiveRecord::Base
  include Likeable

  belongs_to :feed

  validates :feed, presence: true
  validates :title, presence: true
  validates :link, presence: true
  validates :body, presence: true
end

app/models/user.rb
# encoding: utf-8

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_and_belongs_to_many :feeds

  include Likeable::UserMethods
end

app/controllers/add_feed_controller.rb
class AddFeedController < ApplicationController
  before_filter :authenticate_user!

  def new
  end

  def create
    Feed.add_feed(params[:url], current_user)
    redirect_to dashboard_path, :notice => _('New Feed successfully added')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def index
    # @feeds = current_user.feeds.includes(:feed_items).page(params[:page]).per(10)
    feeds_ids = current_user.feeds.map { |i| i.id }
    @feed_items = FeedItem.where(feed_id: feeds_ids).page(params[:page]).per(10)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :redirect_if_logged_in

  def index
  end

private

  def redirect_if_logged_in
    if user_signed_in?
      redirect_to dashboard_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/add_feed_helper.rb
module AddFeedHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
  case level
  when :notice then 'info'
  when :error then 'error'
  when :alert then 'warning'
  end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/add_feed/new.html.erb
<h1>Add Feed:</h1>

<%= form_tag add_feed_create_path, :method => :post, :class => 'well' do %>
  <label for="url">Url:</label>
  <%= text_field_tag :url, nil, :class => 'span8' %>
  <%= submit_tag "Add", :class => 'btn' %>
<% end %>

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>

<!-- <%# @feeds.each do |feed| %>
  <h2><%#= feed.title %></h2>
  <%# feed.feed_items.each do |item| %>
    <div class="span7 well">
      <h3><%#= link_to item.title, item.link %></h3>
      <p><%#= item.body.html_safe %></p>
      <div class="btn-group">
        <a href="#"><i class="icon-star-empty">&nbsp;</i>&nbsp;Star</a>
        <a href="#"><i class="icon-star">&nbsp;</i>&nbsp;Un-Star</a>
        <a href="#"><i class="icon-heart">&nbsp;</i>&nbsp;Like</a>
        <a href="#"><i class="icon-retweet">&nbsp;</i>&nbsp;Share</a>
        <a href="#"><i class="icon-comment">&nbsp;</i>&nbsp;Share with comment</a>
      </div>
    </div>
  <%# end %>
<%# end %>

<div class="span7 well">
  <%#= paginate @feeds %>
  <%#= puts @feeds.first.title %>
</div> -->

<% @feed_items.each do |item| %>
  <div class="span7 well">
    <h3><%= link_to "[#{item.feed.title}] #{item.title}", item.link %></h3>
    <p><%= item.body.html_safe %></p>
    <div class="btn-group">
      <a href="#"><i class="icon-star-empty">&nbsp;</i>&nbsp;Star</a>
      <a href="#"><i class="icon-star">&nbsp;</i>&nbsp;Un-Star</a>
      <a href="#"><i class="icon-heart">&nbsp;</i>&nbsp;Like</a>
      <a href="#"><i class="icon-retweet">&nbsp;</i>&nbsp;Share</a>
      <a href="#"><i class="icon-comment">&nbsp;</i>&nbsp;Share with comment</a>
    </div>
  </div>
<% end %>

<div class="span7 well">
  <%= paginate @feed_items %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Reader</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <!-- devise stuff -->
    <div style='display: none;'>
      <p class='notice'><%= notice %></p>
      <p class='alert'><%= alert %></p>
    </div>
    <!-- end devise stuff -->

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="i-bar"></span>
            <span class="i-bar"></span>
            <span class="i-bar"></span>
          </a>
          <a class="brand" href="/">Reader</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <% if user_signed_in? %>
                <li><%= link_to _('Sign out'), destroy_user_session_path, :method => :delete %></li>
              <% else %>
                <li><%= link_to _('Sign in'), new_user_session_path %></li>
                <li><%= link_to _('Sign up'), new_user_registration_path %></li>
              <% end %>
              <li><%= link_to _('About'), about_path  %></li>
            </ul>

            <form class="navbar-search pull-right" action="">
              <input type="text" class="search-query span2" placeholder="Search">
            </form>

          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="content">
          <div class="row">
            <div class="span9">
            <% [:notice, :error, :alert].each do |level| %>
            <% unless flash[level].blank? %>
             <div data-alert="alert" class="alert alert-<%= flash_class(level) %> fade in">
                <a class="close" data-dismiss="alert" href="#">&times;</a>
                <%= content_tag :p, flash[level] %>
              </div>
              <% end %>
            <% end %>
            <%= yield %>
            </div>
            <div class="span1">&nbsp;</div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                 <ul class="nav nav-list">
                    <li class="nav-header">Sidebar</li>
                    <li><%= link_to _('Add Feed'), add_feed_path %></li>
                    <li><%= link_to _('Feeds'), "#"  %></li>
                    <li><%= link_to _('Comments'), "#"  %></li>
                </ul>
            </div>
           </div>
          </div>
        </div>

      <footer>
        <p>&copy;&nbsp;2012&nbsp;Igor Zubkov</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>Simple Reader</p>